# Generated by Django 5.1.3 on 2024-11-22 06:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Max 60 characters for optimal SEO', max_length=60)),
                ('seo_description', models.CharField(blank=True, help_text='Max 160 characters for optimal SEO', max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=200)),
                ('og_image', models.ImageField(blank=True, help_text='Image for social sharing', upload_to='seo/')),
                ('canonical_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('date', models.DateField()),
                ('read_time', models.CharField(max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('published', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
